
{% set name = "scraps" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scraps-{{ version }}.tar.gz
  sha256: 786c1ee97e416b39e157a219f01308863f47c5a619e4ae559ec63deabea8c3dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - emcee >=2.2.1
    - lmfit >=0.9.5
    - matplotlib-base >=2.0
    - numpy >=1.5
    - pandas >=0.18
    - python >=2.7
    - scipy >=0.14

test:
  imports:
    - scraps

about:
  home: http://github.com/FaustinCarter/scraps
  summary: SuperConducting Resonator Analysis and Plotting Software.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - FaustinCarter
